config/routes.rb
Rails.application.routes.draw do

  root 'home#top'
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :posts do
  	resource :comments, only: [:create, :destroy]
  	resource :likes, only: [:create, :destroy]
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  get 'user/:id/follows' => 'relationships#follows', as: 'follows'
  get 'user/:id/followers' => 'relationships#followers', as: 'followers'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :comment, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploaders :image, ImageUploader #carrierwave関連
	serialize :image
	
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy

	validates :title, presence: true
	validates :body, presence: true
  validates :image, presence: true

  def liked_by?(user)
  	likes.where(user_id: user.id).exists?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :likes, dependent: :destroy

	has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
	has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
	has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
	has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  validates :name, presence: true

	# ユーザーをフォローする
	def follow(user_id)
	  follower.create(followed_id: user_id)
	end

	# ユーザーのフォローを外す
	def unfollow(user_id)
	  follower.find_by(followed_id: user_id).destroy
	end

	# フォローしていればtrueを返す
	def following?(user)
	  following_user.include?(user)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    posts_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new(comment_params)
		@comment.user_id = current_user.id
		@comment.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		@comment = Comment.find(params[:post_id])
		@comment.destroy
		redirect_back(fallback_location: root_path)
	end

	private
	def comment_params
		params.require(:comment).permit(:comment)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
		post = Post.find(params[:post_id])
		like = current_user.likes.new(post_id: post.id)
		like.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		post = Post.find(params[:post_id])
		like = current_user.likes.find_by(post_id: post.id)
		like.destroy
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
  	@post.user_id = current_user.id
  	@post.save
  	redirect_to posts_path
  end

  def show
  	@post = Post.find(params[:id])
  	@user = User.find(params[:id])
    @comment = Comment.new
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
  	@post = Post.find(params[:id])
  	@post.update(post_params)
  	redirect_to post_path(@post)
  end

  def destroy
  	post = Post.find(params[:id])
  	post.destroy
  	redirect_to user_path(current_user)
  end

  private
  def post_params
  	params.require(:post).permit(:title, :body, {image: []})
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

	def follow
	  current_user.follow(params[:id])
	  redirect_back(fallback_location: root_path)
	end

	def unfollow
	  current_user.unfollow(params[:id])
	  redirect_back(fallback_location: root_path)
	end

  def follows
  	@user = User.find(params[:id])
  	@follows = @user.following_user
  end

  def followers
  	@user = User.find(params[:id])
  	@followers = @user.follower_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@posts = @user.posts
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	redirect_to user_path(current_user)
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<h1>Home#top</h1>
<p>Find me in app/views/home/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cyclist1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/7bbd65d6f8.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <header>
    <nav class="navbar navbar-default  navbar-fixed-top">
      <div class="container">
       <div class="navbar-header">
        <h3 class="text-style"><label><%= link_to "cyclist", posts_path %></label></h3>
       </div>

       <div id="slidemenu">
        <ul class="nav navbar-nav navbar-right">


          <% if user_signed_in? %> <!-- ユーザーがログインしているか調べる -->

            <li><%= link_to user_path(current_user.id) do %><span class="glyphicon glyphicon-home" aria-hidden="true">
            </span> Home<% end %></li>

            <li><%= link_to "マイページ", user_path(current_user) %></li>

            <li><%= link_to "投稿", new_post_path %></li>

            <li><%= link_to destroy_user_session_path, method: :delete do %><span class="glyphicon glyphicon-log-in" aria-hidden="true">
            </span> logout<% end %></li>

          <% else %>
  <!-- ユーザーがログインしていなかった時の処理 -->
            <li><%= link_to root_path do %><span class="glyphicon glyphicon-home" aria-hidden="true">
            </span> Home<% end %></li>

            <li><%= link_to new_user_registration_path do %><span class="glyphicon glyphicon-edit" aria-hidden="true">
            </span> sign up<% end %></li>

            <li><%= link_to new_user_session_path do %><span class="glyphicon glyphicon-log-in" aria-hidden="true">
            </span> login<% end %></li>

          <% end %>
        </ul>
      </div>
      </div>
    </nav>
   </header>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<h2>投稿編集</h2>

			<%= form_for(@post) do|f| %>

			<div class="field">
				<%= f.label :title %>
				<%= f.text_field :title %>
			</div>

			<div class="field row">
				<%= f.label :image %>
				<%= f.file_field :image, :multiple => true %>
			</div>

			<div class="field">
				<%= f.label :body %>
				<%= f.text_area :body %>
			</div>

			<div class="actions">
				<%= f.submit %>
			</div>

			<% end %>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<h3>投稿一覧</h3>

			<table>
				<tbody>
					<% @posts.each do |post| %>
					<td>
						<div class="topbox">
							<%= link_to post_path(post) do %>
							<%= image_tag post.image[0].to_s, size:"250x250" %>
							<% end %>
						</div>
							<%= post.title %>
					</td>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<h3>投稿</h3>

			<%= form_for(@post) do|f| %>

			<div class="field">
				<%= f.label :title %>
				<%= f.text_field :title %>
			</div>

			<div class="field row">
				<%= f.label :image %>
				<%= f.file_field :image, :multiple => true %>
			</div>

			<div class="field">
				<%= f.label :body %>
				<%= f.text_area :body %>
			</div>

			<div class="actions">
				<%= f.submit %>
			</div>

			<% end %>

		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<h3>投稿詳細</h3>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-2 col-xs-offset-1">
			<% @post.image.each do |image| %>
				<%= image_tag(image.url, size:"250x250") %>
			<% end %>
		</div>
		<div class="col-xs-8 col-xs-offset-1">
			<div class="row">
				<div class="col-xs-2 ">
					<div>商品名</div>
				</div>
				<div class="col-xs-6">
					<%= @post.title %>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-2 ">
					<div>説明</div>
				</div>
				<div class="col-xs-6">
					<%= @post.body %>
				</div>
			</div>
				<%= link_to "編集", edit_post_path(@post) %><br>
				<%= link_to user_path(@user) do %>
				<%= @user.name %><br>
				<% end %>

<!-- いいね -->
					  <% if @post.liked_by?(current_user) %>
					    <td>
					    	<%= link_to post_likes_path(@post), method: :delete do %>
					    	<i class="fas fa-heart" style="color: red;"></i>
					    	<%= @post.likes.count %>
					    	<% end %>
					    </td>
					  <% else %>
					  	<td>
					  		<%= link_to post_likes_path(@post), method: :post do %>
					  		<i class="far fa-heart"-o aria-hidden="true"></i>
					  		<%= @post.likes.count %>
					  		<% end %>
					  	</td>
					  <% end %>
		</div>
	</div>

		<h4>コメント</h4>
		<table class="table">

			<% @post.comments.each do |comment| %>
			  <tr>
				<td>
				  <%= link_to(comment.user) do %>
					<%= attachment_image_tag(comment.user, :profile_image, size:"50x50", fallback: "no_image.png") %>
			      <% end %>
			    </td>
				<td><%= comment.comment %></td>
				<% if comment.user_id == current_user.id %>
				<td><%= link_to "削除", post_comments_path(comment), method: :delete, class:"pull-right" %></td>
				<% end %>

			  </tr>
			<% end %>

		</table>

<div class="container">
	<div class="row">
		<div class="col-xs-7 col-xs-offset-5">
			<%= form_for [@post, @comment] do |f| %>
			<%= f.text_area :comment, rows:"5", class:"form-control", placeholder:"コメントここに" %>
			<%= f.submit "送信する", class:"pull-right" %>
			<% end %>
		</div>
	</div>
</div>

app/views/relationships/followers.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<h3>フォロワー一覧</h3>

		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="5"></th>
				</tr>
			</thead>

			<tbody>
				<% @followers.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, size: '50x50', fallback: "no_image.png") %></td>
					<td><%= user.name%></td>

					<td>フォロー数 : <%= user.follower.count %></td>
					<td>フォロワー数 : <%= user.followed.count %></td>
					<td><%= link_to "Show", user_path(user.id) %></td>
				</tr>
				<% end %>
			</tbody>
		</table>


		</div>
	</div>
</div>

app/views/relationships/follows.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<h3>フォロー一覧</h3>

		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="5"></th>
				</tr>
			</thead>

			<tbody>
				<% @follows.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, size: '50x50', fallback: "no_image.png") %></td>
					<td><%= user.name%></td>

					<td>フォロー数 : <%= user.follower.count %></td>
					<td>フォロワー数 : <%= user.followed.count %></td>
					<td><%= link_to "Show", user_path(user.id) %></td>
				</tr>
				<% end %>
			</tbody>
		</table>


		</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<h2>編集</h2>

			<%= form_for(@user) do|f| %>

			<div class="field">
				<%= f.label :名前 %>
				<%= f.text_field :name %>
			</div>

			<div class="field">
				<%= f.label :写真変更 %>
				<%= f.attachment_field :profile_image %>
			</div>

			<div class="field">
				<%= f.label :自己紹介 %>
				<%= f.text_area :introduction %>
			</div>

			<div class="actions">
				<%= f.submit %>
			</div>

			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<h3>マイページ</h3>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-2 col-xs-offset-1">
			<%= attachment_image_tag(@user, :profile_image, size: "200x200", fallback: "no_image.jpg") %>
		</div>
		<div class="col-xs-8 col-xs-offset-1">
			<div class="row">
				<div class="col-xs-2 ">
					<div>名前</div>
				</div>
				<div class="col-xs-6">
					<%= @user.name %>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-2 ">
					<div>自己紹介</div>
				</div>
				<div class="col-xs-6">
					<%= @user.introduction %>
				</div>
			</div>

					<% if @user.id != current_user.id %>
			      <% if current_user.following?(@user) %>
    				<%= link_to 'フォロー外す', unfollow_path(@user.id), method: :delete %>
  				  <% else %>
    				<%= link_to 'フォローする', follow_path(@user.id), method: :post %>
  				  <% end %>
      		<% end %>

      		<%= link_to follows_path(@user) do %><%= @user.follower.count %> フォロー中<% end %><br>
      		<%= link_to followers_path(@user) do %><%= @user.followed.count %> フォロワー<% end %><br>
				<%= link_to "編集", edit_user_path(@user) %>
		</div>
	</div>

	<div class="row">
		<div class="col">
			<table>
				<tbody>
					<% @posts.each do |post| %>
					<td>
						<div class="topbox">
							<%= link_to post_path(post) do %>
							<%= image_tag post.image[0].to_s, size:"250x250" %>
							<% end %>
						</div>
							<%= post.title %>
					</td>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>